# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\project1742gui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1194, 643)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.connect_label = QtWidgets.QLabel(self.centralwidget)
        self.connect_label.setGeometry(QtCore.QRect(10, 10, 81, 31))
        self.connect_label.setObjectName("connect_label")
        self.comport_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.comport_combobox.setGeometry(QtCore.QRect(90, 10, 82, 28))
        self.comport_combobox.setObjectName("comport_combobox")
        self.connect_button = QtWidgets.QPushButton(self.centralwidget)
        self.connect_button.setGeometry(QtCore.QRect(180, 10, 83, 29))
        self.connect_button.setObjectName("connect_button")
        self.disconnect_button = QtWidgets.QPushButton(self.centralwidget)
        self.disconnect_button.setGeometry(QtCore.QRect(270, 10, 83, 29))
        self.disconnect_button.setObjectName("disconnect_button")
        self.startrecording_button = QtWidgets.QPushButton(self.centralwidget)
        self.startrecording_button.setGeometry(QtCore.QRect(650, 10, 531, 71))
        self.startrecording_button.setObjectName("startrecording_button")
        self.data_treeview = QtWidgets.QTreeView(self.centralwidget)
        self.data_treeview.setGeometry(QtCore.QRect(10, 140, 371, 491))
        self.data_treeview.setObjectName("data_treeview")
        self.user_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.user_lineedit.setGeometry(QtCore.QRect(90, 60, 171, 28))
        self.user_lineedit.setObjectName("user_lineedit")
        self.user_label = QtWidgets.QLabel(self.centralwidget)
        self.user_label.setGeometry(QtCore.QRect(10, 60, 81, 31))
        self.user_label.setObjectName("user_label")
        self.adduser_button = QtWidgets.QPushButton(self.centralwidget)
        self.adduser_button.setGeometry(QtCore.QRect(270, 60, 83, 29))
        self.adduser_button.setObjectName("adduser_button")
        self.gesture1_label = QtWidgets.QLabel(self.centralwidget)
        self.gesture1_label.setGeometry(QtCore.QRect(10, 100, 81, 31))
        self.gesture1_label.setObjectName("gesture1_label")
        self.gesture_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.gesture_lineedit.setGeometry(QtCore.QRect(90, 100, 171, 28))
        self.gesture_lineedit.setObjectName("gesture_lineedit")
        self.addgestre_button = QtWidgets.QPushButton(self.centralwidget)
        self.addgestre_button.setGeometry(QtCore.QRect(270, 100, 83, 29))
        self.addgestre_button.setObjectName("addgestre_button")
        self.gesture_commbobox = QtWidgets.QComboBox(self.centralwidget)
        self.gesture_commbobox.setGeometry(QtCore.QRect(700, 90, 481, 31))
        self.gesture_commbobox.setObjectName("gesture_commbobox")
        self.gesture2_label = QtWidgets.QLabel(self.centralwidget)
        self.gesture2_label.setGeometry(QtCore.QRect(650, 90, 41, 31))
        self.gesture2_label.setObjectName("gesture2_label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connect_label.setText(_translate("MainWindow", "Порт"))
        self.connect_button.setText(_translate("MainWindow", "Подключиться"))
        self.disconnect_button.setText(_translate("MainWindow", "Отключиться"))
        self.startrecording_button.setText(_translate("MainWindow", "Начать запись"))
        self.user_label.setText(_translate("MainWindow", "Испытуемый"))
        self.adduser_button.setText(_translate("MainWindow", "Добавить"))
        self.gesture1_label.setText(_translate("MainWindow", "Жест"))
        self.addgestre_button.setText(_translate("MainWindow", "Добавить"))
        self.gesture2_label.setText(_translate("MainWindow", "Жест"))
